# -*- coding: utf-8 -*-
"""codigoclase14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkbSTsUQCJMHFvWqH3hZiFfHy-7ZJXgU
"""

import streamlit as st
st.title("mi primera aplicacion en streamlit")
st.header("este es un encabezado")
st.subheader("este es un subencabezado")
st.write("esto es un texto")